- .github/workflows/build.yml
- docs/requirements.txt
- requirements.txt
Closes #20, the issue was that we referenced the deprecated git repo for jupyter-book.
> Fix jupyter-book build

- hub.jupytearth.org-image/Dockerfile
Some of these are redundant and already listed in the pangeo image, but I didn't have time to scan them all one by one - this is my "canonical" package list from my default `conda-setup` home script. We might as well have all of these packages in...
I also put in some of the config and debian packages from my previous course, based on my experience with having a good setup for students to do 100% of their work on the hub.
> Update Dockerfile with "full stack" JupyterLab

- hub.jupytearth.org-image/Dockerfile
- Add ipydrawio, the new jupyterlab-drawio for jupyterlab 3+
- Rely on plotly 5+ to be jupyterlab 3 compatible
> Add drawio IDE and cleanup outdated plotly dependencies

- hub.jupytearth.org-image/Dockerfile
- Update pangeo-notebook base image
- Bump jupyterlab==3.1.0a1 to 3.1.0rc1
> hub image: update pangeo-notebook base image and jupyterlab from alpha to rc1

- docs/index.md
The existing links don't work, and clicking on them directs to `about:blank#blocked` pages in the browser.
> Fix broken NSF award links

- hub.jupytearth.org-image/Dockerfile
I understand the `pyMC3` package would be useful for Abby and @facusapienza21 so I'll attempt to install it according to these instructions: https://github.com/pymc-devs/pymc/wiki/Installation-Guide-(Linux)
> hub image: attempt to install pyMC3

- hub.jupytearth.org-image/Dockerfile
Removing `compilers` was discussed in https://github.com/pangeo-data/jupyter-earth/issues/104#issuecomment-1048602910.
We have some issues with pymc3 that in turn will compile C(++?) things. This is an attempt to not have the `compilers` package modify our `LD_LIBRARY_PATH` in a way that breaks pymc3. The idea is that that could explain a failure that isn't around when among other things - `compilers` isn't around.
Note that removing `compilers` reverts an attempt to resolve issues with `regreg` experienced by @jonathan-taylor, as discussed on slack: https://fperezgroup.slack.com/archives/CU01JGHJ6/p1625699692293600?thread_ts=1625689725.285900&cid=CU01JGHJ6
> Attempt remove compilers package - will pymc3 run?

- hub.jupytearth.org-image/Dockerfile
- hub image: add note about removing workaround
- hub image: require modern version of jupyterlab
> Update JupyterLab to 3.3.0

- hub.jupytearth.org-image/Dockerfile
Closes #101 by removing a no longer needed workaround.
> hub image: remove manual mamba upgrade workaround

- hub.jupytearth.org-image/Dockerfile
The most important one is the github scoped creds tool, the other is mostly convenience.
@consideRatio - this is so we can more easily push/pull from github with @yuvipanda's scoped creds tool.  I tried using it but I'm getting:
So perhaps there's more than installing the package to do?
> Add github scoped creds and jupyterlab favorites

- hub.jupytearth.org-image/Dockerfile
Followup to #122, cleaning up the old version of `gh-scoped-creds`, named `github-app-user-auth`.
> Remove old version of gh-scoped-creds

- hub.jupytearth.org-image/Dockerfile
I could not confirm this made sense, as we copy only a symbolic link, and that link points to what is already made available. So in practice, it seems like we at best expose what is available with a new link.
Overall, I don't see this to cause failures though, so for now, lets try it.
Closes #126.
> hub image: julia workaround, not sure if its needed

- hub.jupytearth.org-image/Dockerfile
This is providing us with `pytorch` and its complicated dependencies without needing to install or maintain the installation ourselves.
> hub image: switch to pangeo/pytorch-notebook as a base image from pangeo/pangeo-notebook

- hub.jupytearth.org-image/Dockerfile
I look to resolve a bug i saw running a hello world like example.
```python
cuLinkAddData(self.handle, enums.CU_JIT_INPUT_PTX,
2686                          ptxbuf, len(ptx), namebuf, 0, None, None)
2687 except CudaAPIError as e:
-> 2688     raise LinkerError("%s\n%s" % (e, self.error_log))
LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.7; current version is '7.4'
```
> hub image: install cuda-compat apt package

- hub.jupytearth.org-image/Dockerfile
This is meant to workaround a bug about the bash terminal failing to open (https://github.com/coder/code-server/issues/5218), as described in https://github.com/pangeo-data/jupyter-earth/issues/137#issuecomment-1187457338
> hub image: downgrade code-server to address regressions (terminal)

- hub.jupytearth.org-image/Dockerfile
It seems the previous strategies to avoid a screensaver wasn't working, and that there is a new version of turbovnc out that seems mainly to be a breaking change for windows users.
> Attempt to avoid a screensaver when using /desktop, bump to turbovnc 3

- hub.jupytearth.org-image/Dockerfile
I'm attempting to address the input/output error reported by @whyjz when starting the default web browser as seen in xfce4 - the graphical UI for our ubuntu linux.
> hub image: install firefox after xfce4

- hub.jupytearth.org-image/Dockerfile
- hub image: install firefox with mamba
- hub image: bump to code-server 4.5.1 with regressions fixed
- hub image: remove workaround resolved by ubuntu 22.04
> Install firefox with mamba and misc cleanup

- .github/workflows/build-image.yaml
We had failing builds because we run out of disk space. We do that when we try to install `qgis` because `qgis` the conda package or some of its dependencies makes us install very very very specific versions of things, which causes us to re-install A LOT of packages.
> ci: increase available disk space before we build image

- hub.jupytearth.org-image/Dockerfile
Closes #126 properly and provides clear documentation on when this workaround is no longer needed etc.
> hub image: patch julia to include stdlibc++.so.6.0.30 from ubuntu 22.04

- hub.jupytearth.org-image/Dockerfile
We tried installing pymc in the base image but never succeeded. What works though is a conda environment in the shared folder called pymc3, and that will work no matter if we uninstall pymc from the base environment.
- Closes #153 
- Closes #105
> hub image: add Min's jupyter-keepalive and cleanup pymc from base image

- hub.jupytearth.org-image/Dockerfile
Ref https://github.com/2i2c-org/infrastructure/issues/2596
> Bump version of Julia

- hub.jupytearth.org-image/Dockerfile
The current pin (to `master`) meant that addressing *any* requested change will immediately pull in a lot of possibly unrelated changes - 6 months worth maybe!
This image was last fully built on Feb 16, and turns out there's a pytorch-notebook pin for that date. So this pins us there, so we can make upgrades more intentionally.
Ref https://github.com/2i2c-org/infrastructure/issues/2596, as the issue that
triggered this.
> Pin base image to a specific version
